import styled from "@emotion/styled";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>2022 Database</h1>

        <ButtonContainer>
          <Button>
            <Link href="login">로그인으로</Link>
          </Button>
          <Button>
            <Link href="db">데이터베이스로</Link>
          </Button>
        </ButtonContainer>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}>
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

const Button = styled.div`
  padding: 15px;
  border-radius: 10px;
  border: 1px solid #666666;
  transition: all 0.5s ease;
  cursor: pointer;
  width: 30%;
  margin: 40px;

  &:hover {
    border: 1px solid blue;
  }
`;

const ButtonContainer = styled.div`
  display: flex;
  flex-directoin: row;
  align-item: center;
  justify-content: center;
  margin: 40px 0px;
  width: 70%;
`;
